spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/review_security_exception"
    username: root
    password: 123123za
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  signerKey: "cub4Rn9DajJWCSTTuZ4VwWK2Nkl+EzMzCb9ooo8ZhGqlo2PlIN7fueT+b7GunCS3fio8u+MsngduMaeDBBPy9Q=="
  valid-duration: 3600 #in second
  refreshable-duaration: 36000 #in second
