spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/review_security_exception"
    username: root
    password: 123123za

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  signerKey: "cub4Rn9DajJWCSTTuZ4VwWK2Nkl+EzMzCb9ooo8ZhGqlo2PlIN7fueT+b7GunCS3fio8u+MsngduMaeDBBPy9Q=="
