package com.review.monkey.security.exception;

import lombok.*;
import lombok.experimental.FieldDefaults;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
@NoArgsConstructor
@AllArgsConstructor
@FieldDefaults(level = AccessLevel.PRIVATE)
public enum ErrorCode {
    // THIS DECLADE  (KEY , MASSAGE)
    // DECLADE AVOID USE NOT CORRECT KEY
    UNCATEGORIZED_EXCEPTION(9999 , "UNCATEGORIZED ERROR", HttpStatus.INTERNAL_SERVER_ERROR),
    KEY_INVALID (1001 , "INVALID MESSAGE KEY" , HttpStatus.BAD_REQUEST),


    USER_EXISTED (1002 , "USER EXISTED", HttpStatus.BAD_REQUEST),


    USERNAME_INVALID (1003 , "USERNAME MUST BE AT LEAST {min} CHARACTERS", HttpStatus.BAD_REQUEST),
    PASSWORD_INVALID (1004 , "PASSWORD MUST BE AT LEAST {min} CHARACTERS", HttpStatus.BAD_REQUEST),
    USER_NOT_EXIST(1005 , "USER NOT EXISTED", HttpStatus.NOT_FOUND),
    UNAUTHENTICATED(1006 , "UNAUTHENTICATED" , HttpStatus.UNAUTHORIZED),
    UNAUTHORIZED(1007 , "YOU DO NOT HAVE PERMISSION" , HttpStatus.FORBIDDEN),
    DOB_INVALID (1008 , "YOUR AGE MUST BE AT LEAST {min}" , HttpStatus.BAD_REQUEST),

    // THIS DECLADE ERROR FOR ROLE
    ROLE_NAME_EXISTED(2000 , "ROLE NAME HAS BEEN EXISTED" , HttpStatus.BAD_REQUEST),
    ROLE_NAME_NOT_FOUND(2001 , "ROLE NAME NOT FOUND" , HttpStatus.BAD_REQUEST),

    // THIS DECLADE ERROR FOR USERROLE
    USER_ID_AND_ROLE_ID_EXISTED (3000 , "USER AND ROLE HAS BEEN EXSITED" , HttpStatus.BAD_REQUEST),

    // THIS DECLADE ERROR FOR PERMISSION
    PERMISSON_NAME_EXISTED (4000 , "PERMISSON HAS BEEN EXISTED" , HttpStatus.BAD_REQUEST),
    // THIS DECALDE ERROR FOR JWT
    HEADER_INVALID (5000  , "HEADER VALID" , HttpStatus.BAD_REQUEST),

    TOKEN_INVALID (5001 , "TOKEN CONTAINS SPACES" , HttpStatus.BAD_REQUEST);
    int code;
    String message;

    // UPDATE HTTSTATUSCODE;
    HttpStatusCode statusCode;
}
